/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.assertj.java-conventions")
}

dependencies {
    api(libs.testng)
    api(project(":assertj-swing"))
    api("org.easytesting:fest-reflect:1.4.1")
    compileOnly(libs.guice)
    testImplementation(libs.junit4)
    testImplementation("org.easytesting:fest-mocks:1.1")
    testImplementation(libs.guice)
}

description = "AssertJ-Swing - TestNG Extension"

tasks.named<Test>("test") {
    useTestNG()
}
