/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.assertj.java-conventions")
}

dependencies {
    api("org.testng:testng:6.11")
    api(project(":assertj-swing"))
    api("org.easytesting:fest-reflect:1.4.1")
    compileOnly("com.google.inject:guice:4.0")
    testImplementation("junit:junit:4.12")
    testImplementation("org.easytesting:fest-mocks:1.1")
    testImplementation("com.google.inject:guice:4.0")
}

description = "AssertJ-Swing - TestNG Extension"

tasks.named<Test>("test") {
    useTestNG()
}
