/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "assertj-swing-parent"
include(":assertj-swing")
include(":assertj-swing-junit")
include(":assertj-swing-junit-jupiter")
include(":fest-util")
include(":fest-test")
include(":fest-reflect")
include(":fest-assert")