/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

rootProject.name = "assertj-swing"
include(":assertj-swing-testng")
include(":assertj-swing")
include(":assertj-swing-junit")
include(":assertj-swing-junit-jupiter")
