/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.assertj.java-conventions")
}

dependencies {
    api("org.assertj:assertj-core:3.17.2")
    api("com.google.code.findbugs:jsr305:3.0.2")
    api("org.easytesting:fest-reflect:1.4.1")
    runtimeOnly("org.easytesting:fest-util:1.2.5")
    testImplementation("org.easytesting:fest-test:2.1.0")
    testImplementation("junit:junit:4.12")
    testImplementation("org.mockito:mockito-core:2.20.1")
    testImplementation("com.googlecode.multithreadedtc:multithreadedtc:1.01")
    testImplementation("nl.jqno.equalsverifier:equalsverifier:2.3.1")
}

description = "AssertJ-Swing"
