/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.assertj.java-conventions")
}

dependencies {
    api(libs.commons.codec)
    api(libs.jupiter)
    api(project(":assertj-swing"))
    api(project(":assertj-swing-junit"))
    api("org.easytesting:fest-reflect:1.4.1")
    compileOnly(libs.ant.junit)
    testImplementation("org.easytesting:fest-test:2.1.0")
    testImplementation("org.easytesting:fest-mocks:1.1")
    testImplementation("nl.jqno.equalsverifier:equalsverifier:2.3.1")
    testImplementation("org.mockito:mockito-core:2.20.1")
    testImplementation(libs.ant.junit)
    testImplementation(libs.jupiter)
}

description = "AssertJ-Swing - JUnit Jupiter Extension"

tasks.named<Test>("test") {
    useJUnitPlatform()
}
