/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.assertj.java-conventions")
}

dependencies {
    api("commons-codec:commons-codec:1.10")
    api("junit:junit:4.12")
    api(project(":assertj-swing"))
    api("org.easytesting:fest-reflect:1.4.1")
    compileOnly("org.apache.ant:ant-junit:1.10.1")
    testImplementation("org.easytesting:fest-test:2.1.0")
    testImplementation("org.easytesting:fest-mocks:1.1")
    testImplementation("nl.jqno.equalsverifier:equalsverifier:2.3.1")
    testImplementation("org.apache.ant:ant-junit:1.10.1")
}

description = "AssertJ-Swing - JUnit Extension"
